### ISSUE TITLE
Multistore support

### ISSUE THREAD

**Issue by bohdanchumak** [redchamps/customer-shopping-carts-tab#2]
It seems like it doesn't support multistores and shows only one cart in the admin panel. Will it work in the same way in Magento 2.3.3 or maybe there is a chance that multistore support will be added?

**Comment by rav-redchamps** [comment]
Possibly, it should be the same. I will try to add the multi-store change to this repo and original pull request as soon as time permits. 

If you are a developer and would like to contribute then please feel free to add a pull request to this repository.

**Comment by rav-redchamps** [comment]
Hi @bohdanchumak 

Please try replacing line#67 of file Block/Adminhtml/ShoppingCartsTab.php

from

return $this->getUrl('customer/*/cart', ['_current' => true]);

to 

return $this->getUrl('customer/*/carts', ['_current' => true]);

this might do the trick. I didn't get time to set up a multi-store environment to test it. But it should work.

Please give it a try and let me know how it works. I will test it myself soon and make a new release in the repo.

**Comment by bohdanchumak** [comment]
Hi @rav-redchamps and thanks for the update.

It works but a bit strange. It works in the way that it shows a separate tab for each website but initially it shows the default website shopping cart content for every tab. However, if you press "Reset filter" button for the specific website tab, it refreshes the tab's content and starts to show the correct products.

**Comment by rav-redchamps** [comment]
Yes, I checked and observed the same behavior.

The problem is in 
**file** vendor/magento/module-quote/Model/QuoteRepository.php 
**function** "getForCustomer" 

It caches quote for customer-id and returns the same when asked multiple times irrespective of website id.

I will check what can be done about it when making a new release to the repo.

----------------------

However, if you would like to use a temporary fix in the  meantime then you can replace line# 242 of 

**file** vendor/magento/module-customer/Block/Adminhtml/Edit/Tab/Cart.php

from

$this->quote = $this->quoteRepository->getForCustomer($customerId, $storeIds);

to

$this->quote = $this->quoteFactory->create()->setSharedStoreIds($storeIds)->loadByCustomer($customerId); 

This will definitely fix the problem.
----------------------

**Comment by rav-redchamps** [comment]
@bohdanchumak released a new version today. This should solve the problem mentioned in this issue.
